{% set version = "3.4.3" %}
{% set name = "xcms" %}
{% set bioc = "3.8" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://github.com/sneumann/xcms/archive/8fc913cc47d97b6492fad79f9d47cf1b4a7d44fa.zip'
  sha256: a687330dfc34ce65c701d1b5a27bc68990cdf28597755c5567a76e5c59e8a3a8
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
# Suggests: BiocStyle, caTools, knitr (>= 1.1.0), faahKO, msdata, ncdf4, rgl, microbenchmark, testthat, pander, magrittr, MALDIquant
requirements:
  host:
    - 'bioconductor-biobase >=2.42.0,<2.43.0'
    - 'bioconductor-biocgenerics >=0.28.0,<0.29.0'
    - 'bioconductor-biocparallel >=1.16.0,<1.17.0'
    - 'bioconductor-massspecwavelet >=1.48.0,<1.49.0'
    - 'bioconductor-msnbase >=2.8.0,<2.9.0'
    - 'bioconductor-multtest >=2.38.0,<2.39.0'
    - 'bioconductor-mzr >=2.16.0,<2.17.0'
    - 'bioconductor-protgenerics >=1.14.0,<1.15.0'
    - 'bioconductor-s4vectors >=0.20.0,<0.21.0'
    - r-base
    - r-lattice
    - r-plyr
    - r-rann
    - r-rcolorbrewer
    - r-robustbase
  run:
    - 'bioconductor-biobase >=2.42.0,<2.43.0'
    - 'bioconductor-biocgenerics >=0.28.0,<0.29.0'
    - 'bioconductor-biocparallel >=1.16.0,<1.17.0'
    - 'bioconductor-massspecwavelet >=1.48.0,<1.49.0'
    - 'bioconductor-msnbase >=2.8.0,<2.9.0'
    - 'bioconductor-multtest >=2.38.0,<2.39.0'
    - 'bioconductor-mzr >=2.16.0,<2.17.0'
    - 'bioconductor-protgenerics >=1.14.0,<1.15.0'
    - 'bioconductor-s4vectors >=0.20.0,<0.21.0'
    - r-base
    - r-lattice
    - r-plyr
    - r-rann
    - r-rcolorbrewer
    - r-robustbase
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>= 2) + file LICENSE'
  summary: 'Framework for processing and visualization of chromatographically separated and single-spectra mass spectral data. Imports from AIA/ANDI NetCDF, mzXML, mzData and mzML files. Preprocesses data for high-throughput, untargeted analyte profiling.'
extra:
  identifiers:
    - biotools:xcms
  parent_recipe:
    name: bioconductor-xcms
    path: recipes/bioconductor-xcms
    version: 3.2.0

